//if[!AUTOGEN_JNA_NATIVES]
/*
 * Copyright 2004-2008 Sun Microsystems, Inc. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * This code is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2
 * only, as published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License version 2 for more details (a copy is
 * included in the LICENSE file that accompanied this code).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this work; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 * Please contact Sun Microsystems, Inc., 16 Network Circle, Menlo
 * Park, CA 94025 or visit www.sun.com if you need additional
 * information or have any questions.
 */

/* **** GENERATED FILE -- DO NOT EDIT ****
 *      This is a CLDC/JNA Interface class definition
 *      generated by com.sun.cldc.jna.JNAGen
 *      from the CLDC/JNA Interface class declaration in ./cldc-native-declarations/src/com/sun/squawk/platform/posix/natives/Ioctl.java
 */
package com.sun.squawk.platform.windows.natives;

import com.sun.cldc.jna.*;

/**
 *
 * java wrapper around #include <sys/ioctl.h>
 */
/*@Includes({"<sys/types.h>", "<sys/ioctl.h>", "<sys/filio.h>"})*/
public interface Ioctl extends Library {

    Ioctl INSTANCE = (Ioctl)
            Native.loadLibrary("RTLD",
                               Ioctl.class);

    /*
     * Ioctl's have the command encoded in the lower word, and the size of
     * any in or out parameters in the upper word.  The high 3 bits of the
     * upper word are used to encode the in/out status of the parameter.
     */

    public final static int IOCPARM_MASK = IoctlImpl.IOCPARM_MASK;		/* parameter length, at most 13 bits */

   // public final static int IOCPARM_MAX = IMPORT;	/* max size of ioctl args */
    /* no parameters */
    public final static int IOC_VOID = IoctlImpl.IOC_VOID;
    /* copy parameters out */
    public final static int IOC_OUT = IoctlImpl.IOC_OUT;
    /* copy parameters in */
    public final static int IOC_IN = IoctlImpl.IOC_IN;
    /* copy paramters in and out */
    public final static int IOC_INOUT = IoctlImpl.IOC_INOUT;
    /* mask for IN/OUT/VOID */
    //public final static int IOC_DIRMASK = IMPORT;


    public final static int FIOCLEX = IoctlImpl.FIOCLEX;		/* set close on exec on fd */
    public final static int FIONCLEX = IoctlImpl.FIONCLEX;		/* remove close on exec */
    public final static int FIONREAD = IoctlImpl.FIONREAD;	/* get # bytes to read */
    public final static int FIONBIO = IoctlImpl.FIONBIO;	/* set/clear non-blocking i/o */
    public final static int FIOASYNC = IoctlImpl.FIOASYNC;	/* set/clear async i/o */
    public final static int FIOSETOWN = IoctlImpl.FIOSETOWN;	/* set owner */
    public final static int FIOGETOWN = IoctlImpl.FIOGETOWN;	/* get owner */
    //public final static int FIODTYPE = IMPORT;	    /* get d_type */


    /**
     * Perform IO control operation <code>request</code> on device <code>fd</code>.
     *
     * @param fd an open file descriptor
     * @param request am encded value containing the requested operation and the arguments
     * @param i1
     * @return -1 on error
     */
    int ioctl(int fd, int request, int i1);

    /**
     * Perorm IO control operation <code>request</code> on device <code>fd</code>.
     *
     * @param fd an open file descriptor
     * @param request am encded value containing the requested operation and the arguments
     * @param i1
     * @param i2
     * @return -1 on error
     */
    int ioctl(int fd, int request, int i1, int i2);

    /**
     * Perorm IO control operation <code>request</code> on device <code>fd</code>.
     *
     * @param fd an open file descriptor
     * @param request am encded value containing the requested operation and the arguments
     * @param i1
     * @param i2
     * @param i3
     * @return -1 on error
     */
    int ioctl(int fd, int request, int i1, int i2, int i3);

}
