

#ifndef COM_PBCFG_H
#define COM_PBCFG_H

#if !(((COM_SW_MAJOR_VERSION == 1) && (COM_SW_MINOR_VERSION == 0)) )
#error Com: Configuration file expected BSW module version to be 1.0.*
#endif

#if !(((COM_AR_RELEASE_MAJOR_VERSION == 4) && (COM_AR_RELEASE_MINOR_VERSION == 0)) )
#error Com: Configuration file expected AUTOSAR version to be 4.0.*
#endif

#include "Com_Types.h"

// COM IPDU IDs
#define COM_PDU_ID_ACKNOWLEDEGMENTSCUPDU					0
#define COM_PDU_ID_PLUGINCOMMUNICATIONSCUTOTCUPDU					1
#define COM_PDU_ID_PLUGINCOMMUNICATIONSCUTOVCUPDU					2
#define COM_PDU_ID_PLUGINCOMMUNICATIONTCUTOSCUPDU					3
#define COM_PDU_ID_PLUGINCOMMUNICATIONVCUTOSCUPDU					4
#define COM_PDU_ID_PLUGININSTALLATIONSCUPDU					5

// COM PDU GROUP IDs
#define COM_PDU_GROUP_ID_RXCOMIPDUGROUP			0
#define COM_PDU_GROUP_ID_TXCOMIPDUGROUP			1

// COM SIGNAL IDs
#define COM_SIGNAL_ID_PLUGINCOMMUNICATIONSCUTOVCUSIGNAL			0
#define COM_SIGNAL_ID_PLUGINCOMMUNICATIONTCUTOSCUSIGNAL			1
#define COM_SIGNAL_ID_PLUGINCOMMUNICATIONVCUTOSCUSIGNAL			2
#define COM_SIGNAL_ID_ACKNOWLEDGEMENTSCUSIGNAL			3
#define COM_SIGNAL_ID_PLUGININSTALLATIONSCUSIGNAL			4
#define COM_SIGNAL_ID_PLUGINCOMMUNICATIONSCUTOTCUSIGNAL			5

// COM GROUP SIGNAL IDs

#endif /* COM_PBCFG_H */
