README FILE FOR CLDC/JNA
12/11/08

This directory contains a set of files for generating a Java interface to C functions, structures and constants.

It is used along with CLDC Java Native Access (com.sun.cldc.jna.*).

The build process starts with the classes the user defines in the interfaces directory. These are abstract classes or
interfaces that describe the describe the C functions, structures, and constants to import from C.

The build-time tool "JNAGen" loads these classes into a Java VM, and (using reflection), generates C code from the java code.
This C code is stored in the "build" directory. The C code, along with optional include files in the "includes"
directory will generate Java classes that have the correct offsets and values to access the C code on the given platform.

This Java implementation code is stored in the "native" directory and can be used by other Java code at runtime.

This directory is structured as follows:
    src          - Java interfaces that describe the C functions, structures, and constants to import from C.
                   This code is only used directly by JNAGen, and may contain Java SE 5.0 features such as annotations.
    preprocessed - Preprocessed verion of src (by std Squawk conditional compilation preprocessor)
    classes      - Compiled java files for preprocessed source code

    build        - C code generated by JNAGen
    includes     - optional include files used by the generated C code in build
    native       - Java source code generated by the C code. Sometimes this source code is created directly in another
                   location. See the -dst option to JNAGen.

