#!/bin/sh
# /etc/init.d/optipos

### BEGIN INIT INFO
# Provides:          optipos
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start optipos on boot
# Description:       Start optipos on boot
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting optipos"
    # run application you want to start
    cd /home/pi/Optipos
    python3 OptiposRPiClient.py SSECorridorMap.json > optipos-trace.txt 2>&1 
    ;;
  stop)
    echo "Stopping optipos"
    # kill application you want to stop
    ;;
  *)
    echo "Usage: /etc/init.d/optipos {start|stop}"
    exit 1
    ;;
esac

exit 0
